export default {
  ww_people: {
    name: 'People',
    fields: [
      ['equalopps', 'Equal opps'],

      ['firstname', 'First name'],
      ['lastname', 'Last name'],
      ['email', 'Email'],
      ['mobile', 'Mobile'],

      ['motivation', 'Motivation'],
      ['achievement', 'Achievement'],
      ['challenge', 'Challenge'],

      ['availability', 'Availability'],
      ['role1', 'Role preference 1'],
      ['role2', 'Role preference 2'],
      ['role3', 'Role preference 3'],
      ['locationpreference', 'Location preference'],
      ['skills', 'Skills'],
      ['cv', 'CV'],
      ['comms', 'How they heard'],

      ['institution', 'Institution'],
      ['qualification', 'Qualification'],
      ['qualificationother', 'Qualification other'],
      ['subjects', 'Subjects'],
      ['grades', 'Grades'],
      ['startdate', 'Start date'],
      ['enddate', 'End date'],

      ['cvconsent', 'CV consent'],

      ['status', 'Status'],
      ['interviewdate', 'Interview date'],
      ['notes', 'Notes'],

      ['af_thrivesunderpressure1', 'AF thrives under pressure 1'],
      ['af_motivationanddrive1', 'AF motivation and drive 1'],
      ['af_committmenttosocialaction1', 'AF committment to social action 1'],
      [
        'fc_crititcalthinkingandprioritisation1',
        'FC crititcal thinking and prioritisation 1',
      ],
      ['fc_attentiontodetail1', 'FC attention to detail 1'],
      ['fc_teamwork1', 'FC teamwork 1'],
      ['fc_planningandorganising1', 'FC planning and organising 1'],
      ['fc_communication1', 'FC communication 1'],
      ['cc_selfawareness1', 'CC self awareness 1'],
      ['cc_adaptability1', 'CC adaptability 1'],
      ['cc_thrivesunderpressure1', 'CC thrives under pressure 1'],
      ['cc_optinmentality1', 'CC opt in mentality 1'],
      ['cc_committmenttosocialaction1', 'CC committment to social action 1'],
      ['cs_creativity1', 'CS creativity 1'],
      [
        'cs_crititcalthinkingandprioritisation1',
        'CS crititcal thinking and prioritisation 1',
      ],
      ['cs_problemdefinition1', 'CS problem definition 1'],
      ['cs_attentiontodetail1', 'CS attention to detail 1'],
      ['cs_planningandorganising1', 'CS planning and organising 1'],
      ['cs_communication1', 'CS communication 1'],
      ['af_thrivesunderpressure2', 'AF thrives under pressure 2'],
      ['af_motivationanddrive2', 'AF motivation and drive 2'],
      ['af_committmenttosocialaction2', 'AF committment to social action 2'],
      [
        'fc_crititcalthinkingandprioritisation2',
        'FC crititcal thinking and prioritisation 2',
      ],
      ['fc_attentiontodetail2', 'FC attention to detail 2'],
      ['fc_teamwork2', 'FC teamwork 2'],
      ['fc_planningandorganising2', 'FC planning and organising 2'],
      ['fc_communication2', 'FC communication 2'],
      ['cc_selfawareness2', 'CC self awareness 2'],
      ['cc_adaptability2', 'CC adaptability 2'],
      ['cc_thrivesunderpressure2', 'CC thrives under pressure 2'],
      ['cc_optinmentality2', 'CC opt in mentality 2'],
      ['cc_committmenttosocialaction2', 'CC committment to social action 2'],
      ['cs_creativity2', 'CS creativity 2'],
      [
        'cs_crititcalthinkingandprioritisation2',
        'CS crititcal thinking and prioritisation 2',
      ],
      ['cs_problemdefinition2', 'CS problem definition 2'],
      ['cs_attentiontodetail2', 'CS attention to detail 2'],
      ['cs_planningandorganising2', 'CS planning and organising 2'],
      ['cs_communication2', 'CS communication 2'],

      ['total', 'Total'],
      ['total_af', 'Total AF'],
      ['total_fc', 'Total FC'],
      ['total_cc', 'Total CC'],
      ['total_cs', 'Total CS'],
      ['total_selfawareness', 'Total self awareness'],
      ['total_adaptability', 'Total adaptability'],
      ['total_thrivesunderpressure', 'Total thrives under pressure'],
      ['total_optinmentality', 'Total opt in mentality'],
      ['total_motivationanddrive', 'Total motivation and drive'],
      ['total_creativity', 'Total creativity'],
      [
        'total_crititcalthinkingandprioritisation',
        'Total crititcal thinking and prioritisation',
      ],
      ['total_problemdefinition', 'Total problem definition'],
      ['total_attentiontodetail', 'Total attention to detail'],
      ['total_teamwork', 'Total teamwork'],
      ['total_planningandorganising', 'Total planning and organising'],
      ['total_communication', 'Total communication'],
      ['total_committmenttosocialaction', 'Total committment to social action'],

      ['skype', 'Skype'],
      ['address', 'Address'],
      ['availabilityold', 'Availability (old)'],
      ['skillswriting', 'Skills writing'],
      ['skillsdigital', 'Skills digital'],
      ['skillsqualitative', 'Skills qualitative'],
      ['skillsgrowth', 'Skills growth'],
      ['skillscomms', 'Skills comms'],
      ['skillsquantitative', 'Skills quantitative'],
      ['skillsfundraising', 'Skills fundraising'],
      ['skillsnetworking', 'Skills networking'],
      ['skillscomplex', 'Skills complex'],
      ['skillstargets', 'Skills targets'],
      ['skillsfrontline', 'Skills frontline'],
      ['skillsdesign', 'Skills design'],
      ['skillsorganising', 'Skills organising'],
      ['commsold', 'How they heard (old)'],
      ['locationpreferences', 'Location preferences (old)'],

      ['id', 'Id'],
      ['createdat', 'Created at'],
      ['modifiedat', 'Modified at'],
    ],
  },
  ww_equalopps: {
    name: 'Equal Opps',
    fields: [
      ['person', 'Person'],

      ['gender', 'Gender'],
      ['orientation', 'Orientation'],
      ['ethnicity', 'Ethnicity'],
      ['ethnicityother', 'Ethnicity other'],
      ['dependents', 'Dependents'],
      ['disability', 'Disability'],
      ['homepostcode', 'Home postcode'],
      ['householdincome', 'Household income'],

      ['id', 'Id'],
      ['createdat', 'Created at'],
      ['modifiedat', 'Modified at'],
    ],
  },
};
